@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" ExamList
UniqueTagList -[hidden]down- ExamList
ExamList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
ExamList -right-> "*" ExamScores
UniquePersonList -right-> Person

Person -up-> "*" Tag
Person -up-> "*" ExamScores

Person *--> Name
Person *--> StudentId
Person *--> Phone
Person *--> Email
Person *--> TelegramHandle
@enduml
